import "./_guard.mjs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("@playwright/test");
const BASE = process.env.BASE ?? "http://localhost:3000", OUT = process.env.OUT, PW = process.env.SEED_USER_PASSWORD;
const browser = await chromium.launch({ channel: "chrome" });
let fails = 0;
const ok = (n, c, e = "") => { console.log(`${c ? "✓" : "✗"} ${n}${e ? " — " + e : ""}`); if (!c) fails++; };
const settle = (p) => p.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
const toastWith = async (p, text) => { await p.locator("[data-sonner-toast]", { hasText: text }).last().waitFor({ timeout: 15000 }).catch(() => {}); return (await p.locator("[data-sonner-toast]", { hasText: text }).count()) > 0; };
async function login(email, viewport = { width: 1440, height: 900 }, scheme = "light") {
  const page = await (await browser.newContext({ viewport, colorScheme: scheme })).newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.errors = errors;
  await page.goto(`${BASE}/entrar`);
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha", { exact: true }).fill(PW);
  await page.getByRole("button", { name: "Entrar" }).click();
  await page.waitForURL(`${BASE}/`, { timeout: 30000 });
  return page;
}
const { createClient } = require("@supabase/supabase-js");
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SECRET_KEY, { auth: { persistSession: false } });
const { data: owner } = await db.from("profiles").select("id").eq("full_name", "Rafael Exemplo").single();
const ANA = (await db.from("students").select("id").eq("first_name", "Ana").eq("last_name", "Duarte").single()).data.id;
const NOC = (await db.from("students").select("id").eq("trainer_id", owner.id).is("health_consent_declared_at", null).is("deleted_at", null).limit(1).single()).data.id;
const page = await login("owner.seed@example.com");
await page.goto(`${BASE}/alunos?editar=${ANA}`); await settle(page);
const modal = page.getByRole("dialog");
const triage = modal.getByRole("region", { name: "Triagem de sinais de alerta" });
ok("bloco de triagem no cadastro", (await triage.count()) === 1);
await triage.getByRole("button", { name: "Registrar triagem" }).click();
const dlg = page.getByRole("dialog", { name: "Registrar triagem" });
await dlg.waitFor();
await dlg.getByRole("button", { name: "Salvar triagem" }).click();
ok("exige marcar algo", (await dlg.getByText(/Marque os sinais/).count()) === 1);
await dlg.getByLabel("Panturrilha ou perna inchada e dolorida").check();
await dlg.getByLabel("Aluno encaminhado a médico/fisioterapeuta").check();
await dlg.getByLabel("Observação (opcional)").fill("Relatou hoje.");
await dlg.getByRole("button", { name: "Salvar triagem" }).click();
ok("triagem salva", await toastWith(page, "Triagem registrada."));
ok("modal do aluno continua aberto", (await page.getByRole("dialog").count()) >= 1 && page.url().includes("editar="));
await triage.getByText(/Sem liberação registrada/).waitFor({ timeout: 15000 }).catch(() => {});
ok("pendência mostrada", (await triage.getByText(/Sem liberação registrada/).count()) === 1, await triage.innerText());
// montador: aviso
const b = await login("owner.seed@example.com");
await b.goto(`${BASE}/treinos/novo?aluno=${ANA}`); await settle(b);
ok("aviso no montador", (await b.getByText("Sinais de alerta relatados/observados sem liberação").count()) === 1);
await b.screenshot({ path: `${OUT}/rf-builder.png` });
// liberação
await triage.getByRole("button", { name: "Registrar liberação" }).click();
const cl = page.getByRole("dialog", { name: "Registrar liberação" });
await cl.waitFor();
await cl.getByRole("combobox", { name: "Quem liberou" }).click();
await page.getByRole("option", { name: "Fisioterapeuta" }).click();
await cl.getByLabel("Nome do profissional").fill("Fisio Exemplo");
await cl.getByRole("button", { name: "Salvar liberação" }).click();
ok("liberação salva", await toastWith(page, "Liberação registrada."));
await triage.getByText(/Liberado por/).waitFor({ timeout: 15000 }).catch(() => {});
ok("liberado no cadastro", (await triage.getByText(/Liberado por Fisioterapeuta \(Fisio Exemplo\)/).count()) === 1);
await page.screenshot({ path: `${OUT}/rf-modal.png` });
await b.reload(); await settle(b);
ok("encaminhamento mostrado", (await triage.getByText("Aluno encaminhado a médico/fisioterapeuta.").count()) === 1);
// aluno sem consentimento de saúde: triagem disponível
const n = await login("owner.seed@example.com");
await n.goto(`${BASE}/alunos?editar=${NOC}`); await settle(n);
const nt = n.getByRole("dialog").getByRole("region", { name: "Triagem de sinais de alerta" });
ok("sem consentimento: bloco de triagem", (await nt.count()) === 1 && (await nt.getByRole("button", { name: "Registrar triagem" }).count()) === 1);
await nt.getByRole("button", { name: "Registrar triagem" }).click();
const nd = n.getByRole("dialog", { name: "Registrar triagem" }); await nd.waitFor();
await nd.getByLabel("Trauma recente (queda, acidente) com dor").check();
await nd.getByRole("button", { name: "Salvar triagem" }).click();
ok("sem consentimento: triagem salva", await toastWith(n, "Triagem registrada."));
ok("aviso sai do montador", (await b.getByText("Sinais de alerta relatados/observados sem liberação").count()) === 0);
ok("sem erros de página", [page, b, n].every((p) => p.errors.length === 0), [page, b, n].flatMap((p) => p.errors).join(" | "));
await browser.close();
console.log(fails ? `${fails} falha(s)` : "tudo ok");
process.exit(fails ? 1 : 0);
