import "./_guard.mjs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("@playwright/test");
const BASE = process.env.BASE ?? "http://localhost:3000", OUT = process.env.OUT, PW = process.env.SEED_USER_PASSWORD;
const browser = await chromium.launch({ channel: "chrome" });
let fails = 0;
const ok = (n, c, e = "") => { console.log(`${c ? "✓" : "✗"} ${n}${e ? " — " + e : ""}`); if (!c) fails++; };
const settle = (p) => p.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
const toastWith = async (p, text) => { await p.locator("[data-sonner-toast]", { hasText: text }).last().waitFor({ timeout: 15000 }).catch(() => {}); return (await p.locator("[data-sonner-toast]", { hasText: text }).count()) > 0; };
async function login(email, viewport = { width: 1440, height: 900 }, scheme = "light") {
  const page = await (await browser.newContext({ viewport, colorScheme: scheme })).newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.errors = errors;
  await page.goto(`${BASE}/entrar`);
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha", { exact: true }).fill(PW);
  await page.getByRole("button", { name: "Entrar" }).click();
  await page.waitForURL(`${BASE}/`, { timeout: 30000 });
  return page;
}
const { createClient } = require("@supabase/supabase-js");
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SECRET_KEY, { auth: { persistSession: false } });
const { data: org } = await admin.from("organizations").select("id").eq("slug", "studio-exemplo").single();
const { data: studs } = await admin.from("students").select("id").eq("organization_id", org.id).order("enrollment_number");
const page = await login("owner.seed@example.com");
await page.goto(`${BASE}/treinos/novo?aluno=${studs[3].id}`); await settle(page);
await page.getByRole("button", { name: "Adicionar exercício" }).click();
const sheet = page.getByRole("dialog");
await sheet.getByLabel("Buscar exercício").fill("agachamento goblet");
const quick = sheet.getByRole("button", { name: /Adicionar Agachamento goblet rápido/ });
await sheet.getByRole("button", { name: /^Abdominal supra/ }).waitFor({ state: "detached" }); // Espera a lista filtrada estabilizar (no build de produção ela ainda se reorganiza e desfaz o hover).
await quick.waitFor(); await page.waitForTimeout(800);
await quick.hover();
const quickTip = page.getByRole("tooltip").filter({ hasText: "Adiciona com os valores padrão e continua escolhendo" }).first();
await quickTip.waitFor({ state: "visible", timeout: 5000 }).catch(() => {});
ok("tooltip do + Rápido", await quickTip.isVisible().catch(() => false));
await quick.click();
ok("toast com resumo", await toastWith(page, "Agachamento goblet adicionado · 3×"));
ok("painel continua aberto", await sheet.isVisible());
const agach = page.locator("[role=tabpanel] li", { hasText: "Agachamento goblet" }).first();
await page.screenshot({ path: `${OUT}/02-rapido.png` });
await sheet.getByLabel("Buscar exercício").fill("dead bug");
await sheet.getByRole("button", { name: /^Dead bug/ }).first().click();
await page.waitForTimeout(800);
ok("clique no nome fecha o painel", !(await page.getByRole("dialog").isVisible().catch(() => false)));
ok("item rápido entra recolhido", (await agach.getByRole("button", { name: /Expandir/ }).count()) === 1 && (await agach.getByLabel("Séries", { exact: true }).count()) === 0);
const dead = page.locator("[role=tabpanel] li", { hasText: "Dead bug" }).first();
const series = dead.getByLabel("Séries", { exact: true });
ok("item aberto", (await series.count()) === 1);
ok("foco no primeiro campo", await series.evaluate((el) => el === document.activeElement));
await page.screenshot({ path: `${OUT}/03-clique-foco.png` });
ok("sem erros de JS", page.errors.length === 0, page.errors.join(" | "));
console.log(fails ? `${fails} falha(s)` : "Tudo ok");
await browser.close();
