import "./_guard.mjs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("@playwright/test");
const BASE = process.env.BASE ?? "http://localhost:3000", OUT = process.env.OUT, PW = process.env.SEED_USER_PASSWORD;
const browser = await chromium.launch({ channel: "chrome" });
let fails = 0;
const ok = (n, c, e = "") => { console.log(`${c ? "✓" : "✗"} ${n}${e ? " — " + e : ""}`); if (!c) fails++; };
const settle = (p) => p.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
const toastWith = async (p, text) => { await p.locator("[data-sonner-toast]", { hasText: text }).last().waitFor({ timeout: 15000 }).catch(() => {}); return (await p.locator("[data-sonner-toast]", { hasText: text }).count()) > 0; };
async function login(email, viewport = { width: 1440, height: 900 }, scheme = "light") {
  const page = await (await browser.newContext({ viewport, colorScheme: scheme })).newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.errors = errors;
  await page.goto(`${BASE}/entrar`);
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha", { exact: true }).fill(PW);
  await page.getByRole("button", { name: "Entrar" }).click();
  await page.waitForURL(`${BASE}/`, { timeout: 30000 });
  return page;
}
const { createClient } = require("@supabase/supabase-js");
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SECRET_KEY, { auth: { persistSession: false } });
const { data: org } = await admin.from("organizations").select("id").eq("slug", "studio-exemplo").single();
const { data: studs } = await admin.from("students").select("id").eq("organization_id", org.id).order("enrollment_number");
const page = await login("owner.seed@example.com");
await page.goto(`${BASE}/treinos/novo?aluno=${studs[3].id}`); await settle(page);
await page.getByLabel("Nome do treino").fill("Teste dica");
await page.getByRole("button", { name: "Adicionar exercício" }).click();
const sheet = page.getByRole("dialog");
await sheet.getByLabel("Buscar exercício").fill("dead bug");
await sheet.getByRole("button", { name: /^Dead bug/ }).first().click();
await page.waitForTimeout(800);
const item = page.locator("[role=tabpanel] li", { hasText: "Dead bug" }).first();
await item.getByRole("button", { name: "Mais opções de Dead bug" }).click();
const ed = item.getByRole("textbox", { name: "Dica" });
await ed.click();
await page.keyboard.type("Coluna neutra");
await page.keyboard.press("Shift+Home");
await item.getByRole("button", { name: "Negrito" }).click();
ok("negrito visível enquanto digita", (await ed.locator("b", { hasText: "Coluna neutra" }).count()) === 1);
ok("botão Negrito pressionado", (await item.getByRole("button", { name: "Negrito" }).getAttribute("aria-pressed")) === "true");
await page.keyboard.press("ArrowRight");
await page.keyboard.press("Enter");
await item.getByRole("button", { name: "Lista" }).click();
ok("negrito continua na linha nova (padrão de editores)", (await item.getByRole("button", { name: "Negrito" }).getAttribute("aria-pressed")) === "true");
await item.getByRole("button", { name: "Negrito" }).click();
await page.keyboard.type("respire");
await page.keyboard.press("Enter");
await page.keyboard.type("sem dor");
ok("lista visível enquanto digita", (await ed.locator("li").count()) === 2);
await page.screenshot({ path: `${OUT}/04-dica-editor.png`, clip: { x: 250, y: 0, width: 1190, height: 900 } });
await page.getByRole("button", { name: "Salvar rascunho" }).click();
ok("salvo", await toastWith(page, "Treino salvo"));
await page.waitForURL(/\/editar/, { timeout: 15000 }).catch(() => {});
const { data: plan } = await admin.from("training_plans").select("id").eq("student_id", studs[3].id).eq("name", "Teste dica").order("created_at", { ascending: false }).limit(1).single();
const { data: w } = await admin.from("plan_workouts").select("id").eq("plan_id", plan.id).single();
const { data: it } = await admin.from("plan_workout_items").select("id, tip").eq("workout_id", w.id).single();
ok("armazenado como texto saneado", it.tip === "**Coluna neutra**\n- respire\n- sem dor", JSON.stringify(it.tip));

// Texto antigo com marcação duplicada: exibido e salvo corrigido
await admin.from("plan_workout_items").update({ tip: "**- **texto****" }).eq("id", it.id);
await page.goto(`${BASE}/treinos/${plan.id}/editar`); await settle(page);
const ed2 = page.locator("[role=tabpanel] li", { hasText: "Dead bug" }).first().getByRole("textbox", { name: "Dica" });
ok("texto antigo aparece corrigido", (await ed2.locator("li b", { hasText: "texto" }).count()) === 1 && !(await ed2.textContent()).includes("*"), await ed2.innerHTML());
await page.goto(`${BASE}/treinos/${plan.id}/imprimir`); await settle(page);
ok("impressão corrigida", (await page.locator("article li strong, article li b", { hasText: "texto" }).count()) === 1 && !(await page.locator("article").textContent()).includes("**"));
await page.goto(`${BASE}/treinos/${plan.id}/editar`); await settle(page);
await page.getByLabel("Nome do treino").fill("Teste dica 2");
await page.getByRole("button", { name: /^Salvar/ }).click();
ok("salvo de novo", await toastWith(page, "Treino salvo"));
const { data: w2 } = await admin.from("plan_workouts").select("id").eq("plan_id", plan.id).single();
const { data: it3 } = await admin.from("plan_workout_items").select("tip").eq("workout_id", w2.id).single();
ok("regravado canônico", it3.tip === "- **texto**", JSON.stringify(it3.tip));
ok("sem erros de JS", page.errors.length === 0, page.errors.join(" | "));
console.log(fails ? `${fails} falha(s)` : "Tudo ok");
await browser.close();
