import "./_guard.mjs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("@playwright/test");
const BASE = process.env.BASE ?? "http://localhost:3000", OUT = process.env.OUT, PW = process.env.SEED_USER_PASSWORD;
const browser = await chromium.launch({ channel: "chrome" });
let fails = 0;
const ok = (n, c, e = "") => { console.log(`${c ? "✓" : "✗"} ${n}${e ? " — " + e : ""}`); if (!c) fails++; };
const settle = (p) => p.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
const toastWith = async (p, text) => { await p.locator("[data-sonner-toast]", { hasText: text }).last().waitFor({ timeout: 15000 }).catch(() => {}); return (await p.locator("[data-sonner-toast]", { hasText: text }).count()) > 0; };
async function login(email, viewport = { width: 1440, height: 900 }, scheme = "light") {
  const page = await (await browser.newContext({ viewport, colorScheme: scheme })).newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.errors = errors;
  await page.goto(`${BASE}/entrar`);
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha", { exact: true }).fill(PW);
  await page.getByRole("button", { name: "Entrar" }).click();
  await page.waitForURL(`${BASE}/`, { timeout: 30000 });
  return page;
}
const { createClient } = require("@supabase/supabase-js");
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SECRET_KEY, { auth: { persistSession: false } });
const { data: org } = await admin.from("organizations").select("id").eq("slug", "studio-exemplo").single();
const { data: studs } = await admin.from("students").select("id").eq("organization_id", org.id).order("enrollment_number");
const page = await login("owner.seed@example.com");
await page.goto(`${BASE}/treinos/novo?aluno=${studs[3].id}`); await settle(page);
await page.getByLabel("Nome do treino").fill("Teste intensidade texto");
await page.getByRole("button", { name: "Adicionar exercício" }).click();
const sheet = page.getByRole("dialog");
await sheet.getByLabel("Buscar exercício").fill("dead bug");
await sheet.getByRole("button", { name: /^Dead bug/ }).first().click();
await page.waitForTimeout(800);
const item = page.locator("[role=tabpanel] li", { hasText: "Dead bug" }).first();
const intensity = item.getByLabel("Intensidade", { exact: true }).first();
ok("intensidade na linha principal (Mais opções fechado)", (await intensity.count()) === 1 && (await item.getByRole("button", { name: "Mais opções de Dead bug" }).getAttribute("aria-expanded")) === "false");
ok("placeholder e limite", (await intensity.getAttribute("placeholder")) === "ex.: 70%" && (await intensity.getAttribute("maxlength")) === "20");
ok("sem seletor RPE|RIR|%1RM", (await item.getByRole("button", { name: "RPE" }).count()) === 0);
await intensity.fill("RPE 8");
await page.screenshot({ path: `${OUT}/08-intensidade-texto.png`, clip: { x: 250, y: 250, width: 1190, height: 450 } });
await item.getByRole("button", { name: /Detalhar séries/ }).click();
await item.getByRole("button", { name: "Gerar a partir do resumo" }).click();
const set1 = item.locator("ol > li").first();
const setInt = set1.getByLabel("Intensidade", { exact: true });
ok("série herda e mostra intensidade na linha principal", (await setInt.inputValue()) === "RPE 8");
await setInt.fill("70%");
await page.getByRole("button", { name: "Salvar rascunho" }).click();
ok("salvo", await toastWith(page, "Treino salvo"));
const { data: plan } = await admin.from("training_plans").select("id").eq("name", "Teste intensidade texto").order("created_at", { ascending: false }).limit(1).single();
const { data: w } = await admin.from("plan_workouts").select("id").eq("plan_id", plan.id).single();
const { data: it } = await admin.from("plan_workout_items").select("id, intensity, intensity_type").eq("workout_id", w.id).single();
const { data: sets } = await admin.from("plan_item_sets").select("intensity").eq("item_id", it.id).order("position");
ok("banco: texto no item e nas séries", it.intensity === "RPE 8" && it.intensity_type === null && sets[0].intensity === "70%" && sets[1].intensity === "RPE 8", JSON.stringify([it, sets]));
await page.goto(`${BASE}/treinos/${plan.id}/imprimir`); await settle(page);
ok("impressão usa o texto", (await page.locator("article").getByText(/70%/).count()) >= 1 && (await page.locator("article").getByText(/RPE 8/).count()) >= 1);
await page.screenshot({ path: `${OUT}/09-impressao.png` });
ok("sem erros de JS", page.errors.length === 0, page.errors.join(" | "));
console.log(fails ? `${fails} falha(s)` : "Tudo ok");
await browser.close();
