import "./_guard.mjs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("@playwright/test");
const BASE = process.env.BASE ?? "http://localhost:3000", PW = process.env.SEED_USER_PASSWORD;
const browser = await chromium.launch({ channel: "chrome" });
let fails = 0;
const ok = (n, c, e = "") => { console.log(`${c ? "✓" : "✗"} ${n}${e ? " — " + e : ""}`); if (!c) fails++; };
const settle = (p) => p.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
const toastWith = async (p, text) => { await p.locator("[data-sonner-toast]", { hasText: text }).last().waitFor({ timeout: 15000 }).catch(() => {}); return (await p.locator("[data-sonner-toast]", { hasText: text }).count()) > 0; };
async function login(email, viewport = { width: 1440, height: 900 }, scheme = "light") {
  const page = await (await browser.newContext({ viewport, colorScheme: scheme })).newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.errors = errors;
  await page.goto(`${BASE}/entrar`);
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha", { exact: true }).fill(PW);
  await page.getByRole("button", { name: "Entrar" }).click();
  await page.waitForURL(`${BASE}/`, { timeout: 30000 });
  return page;
}
const page = await login("owner.seed@example.com");
await page.goto(`${BASE}/treinos/novo`); await settle(page);
await page.getByLabel("Nome do treino").fill("Teste subida");
await page.getByRole("button", { name: "Adicionar exercício" }).click();
const sheet = page.getByRole("dialog");
await sheet.getByLabel("Buscar exercício").fill("dead bug");
await sheet.getByRole("button", { name: /^Dead bug/ }).first().click();
await page.waitForTimeout(800);
const item = page.locator("[role=tabpanel] li", { hasText: "Dead bug" }).first();
await item.getByRole("button", { name: "Mais opções de Dead bug" }).click();
await item.getByRole("combobox", { name: /^Unidade(?! da carga)/ }).click();
ok("opções Subida e Descida", (await page.getByRole("option", { name: "Subida" }).count()) === 1 && (await page.getByRole("option", { name: "Descida" }).count()) === 1);
await page.getByRole("option", { name: "Subida" }).click();
const min = item.getByLabel("Subida Mín.");
ok("rótulo e teclado numérico", (await min.count()) === 1 && (await min.getAttribute("inputmode")) === "numeric");
await min.fill("2,5");
await page.getByRole("button", { name: "Salvar modelo" }).or(page.getByRole("button", { name: /^Salvar/ })).first().click();
await page.waitForTimeout(800);
ok("fracionado recusado", (await item.getByText(/inteir/i).count()) >= 1);
await min.fill("10");
await page.getByRole("button", { name: /^Salvar/ }).first().click();
ok("salvo", await toastWith(page, "salvo"));
ok("sem erros de JS", page.errors.length === 0, page.errors.join(" | "));
console.log(fails ? `${fails} falha(s)` : "Tudo ok");
await browser.close();
