-- =============================================================================
-- Fase 2 — Dados de referência: catálogo global de condições e biblioteca
-- global com 52 exercícios comuns. SEM contraindicações: regras globais só
-- entram por migration após revisão/aprovação do responsável técnico
-- (ver docs/revisao/contraindicacoes-sugeridas.csv).
-- =============================================================================

insert into public.health_conditions (key, name) values
  ('lombar', 'Coluna lombar'),
  ('cervical', 'Coluna cervical'),
  ('ombro', 'Ombro'),
  ('cotovelo_punho', 'Cotovelo e punho'),
  ('quadril', 'Quadril'),
  ('joelho', 'Joelho'),
  ('tornozelo_pe', 'Tornozelo e pé'),
  ('hipertensao', 'Hipertensão arterial'),
  ('cardiopatia', 'Cardiopatia'),
  ('gestacao', 'Gestação'),
  ('osteoporose', 'Osteoporose')
on conflict (key) do nothing;

insert into public.exercises (name, muscle_groups, equipment, instructions, created_by) values
  ('Supino reto com barra', '{peitoral,triceps,ombros}'::text[], 'Barra e banco', 'Deitado no banco, desça a barra até a linha do peito e empurre até estender os cotovelos.', null),
  ('Supino reto com halteres', '{peitoral,triceps,ombros}'::text[], 'Halteres e banco', 'Deitado no banco, desça os halteres ao lado do peito e empurre para cima.', null),
  ('Supino inclinado com halteres', '{peitoral,ombros,triceps}'::text[], 'Halteres e banco inclinado', 'Banco inclinado a 30–45°, desça os halteres ao lado do peito e empurre para cima.', null),
  ('Crucifixo com halteres', '{peitoral}'::text[], 'Halteres e banco', 'Com cotovelos levemente flexionados, abra os braços em arco e retorne unindo os halteres acima do peito.', null),
  ('Crossover na polia', '{peitoral}'::text[], 'Polia dupla', 'Em pé entre as polias, traga as mãos à frente do corpo em arco, cotovelos levemente flexionados.', null),
  ('Flexão de braços', '{peitoral,triceps,ombros,abdomen}'::text[], 'Peso corporal', 'Corpo alinhado, desça o peito em direção ao chão e empurre até estender os cotovelos.', null),
  ('Puxada frontal na polia', '{dorsais,biceps}'::text[], 'Polia alta', 'Sentado, puxe a barra até a parte superior do peito levando os cotovelos para baixo.', null),
  ('Remada baixa sentada na polia', '{dorsais,biceps,trapezio}'::text[], 'Polia baixa', 'Sentado com tronco estável, puxe o triângulo em direção ao abdômen aproximando as escápulas.', null),
  ('Remada curvada com barra', '{dorsais,trapezio,biceps,lombar}'::text[], 'Barra', 'Tronco inclinado à frente com coluna neutra, puxe a barra em direção ao abdômen.', null),
  ('Remada unilateral com halter', '{dorsais,biceps}'::text[], 'Halter e banco', 'Apoiado no banco, puxe o halter em direção ao quadril mantendo o tronco estável.', null),
  ('Barra fixa', '{dorsais,biceps}'::text[], 'Barra fixa', 'Pendurado, puxe o corpo até o queixo passar a barra e desça com controle.', null),
  ('Pullover com halter', '{dorsais,peitoral}'::text[], 'Halter e banco', 'Deitado, leve o halter por trás da cabeça com cotovelos semiflexionados e retorne acima do peito.', null),
  ('Levantamento terra', '{posteriores,gluteos,lombar,dorsais}'::text[], 'Barra', 'Com a barra junto às pernas e coluna neutra, estenda quadril e joelhos até ficar em pé.', null),
  ('Levantamento terra romeno', '{posteriores,gluteos,lombar}'::text[], 'Barra ou halteres', 'Joelhos levemente flexionados, leve o quadril para trás descendo a carga junto às pernas e retorne.', null),
  ('Agachamento livre com barra', '{quadriceps,gluteos,posteriores}'::text[], 'Barra e rack', 'Barra nas costas, flexione quadril e joelhos descendo com tronco estável e suba.', null),
  ('Agachamento goblet', '{quadriceps,gluteos}'::text[], 'Halter ou kettlebell', 'Segurando a carga junto ao peito, agache mantendo o tronco ereto e suba.', null),
  ('Leg press 45°', '{quadriceps,gluteos}'::text[], 'Leg press', 'Com os pés na plataforma, flexione os joelhos com controle e empurre até quase estender.', null),
  ('Cadeira extensora', '{quadriceps}'::text[], 'Cadeira extensora', 'Sentado, estenda os joelhos elevando o apoio e retorne com controle.', null),
  ('Mesa flexora', '{posteriores}'::text[], 'Mesa flexora', 'Deitado de bruços, flexione os joelhos trazendo o apoio em direção aos glúteos.', null),
  ('Cadeira flexora', '{posteriores}'::text[], 'Cadeira flexora', 'Sentado, flexione os joelhos empurrando o apoio para baixo e retorne com controle.', null),
  ('Afundo com halteres', '{quadriceps,gluteos}'::text[], 'Halteres', 'Dê um passo à frente e desça até ambos os joelhos formarem cerca de 90°; retorne.', null),
  ('Agachamento búlgaro', '{quadriceps,gluteos}'::text[], 'Banco e halteres', 'Com o pé de trás apoiado no banco, desça flexionando o joelho da frente e suba.', null),
  ('Elevação pélvica', '{gluteos,posteriores}'::text[], 'Barra e banco', 'Costas apoiadas no banco, eleve o quadril com a barra sobre ele até alinhar tronco e coxas.', null),
  ('Ponte de glúteos', '{gluteos,posteriores}'::text[], 'Peso corporal', 'Deitado com joelhos flexionados, eleve o quadril contraindo os glúteos e desça.', null),
  ('Cadeira abdutora', '{abdutores,gluteos}'::text[], 'Cadeira abdutora', 'Sentado, afaste as pernas contra a resistência e retorne com controle.', null),
  ('Cadeira adutora', '{adutores}'::text[], 'Cadeira adutora', 'Sentado, aproxime as pernas contra a resistência e retorne com controle.', null),
  ('Panturrilha em pé', '{panturrilhas}'::text[], 'Máquina ou degrau', 'Em pé, eleve os calcanhares o máximo possível e desça com controle.', null),
  ('Panturrilha sentado', '{panturrilhas}'::text[], 'Máquina', 'Sentado com a carga sobre os joelhos, eleve os calcanhares e desça com controle.', null),
  ('Desenvolvimento com halteres', '{ombros,triceps}'::text[], 'Halteres e banco', 'Sentado, empurre os halteres acima da cabeça e desça até a altura das orelhas.', null),
  ('Desenvolvimento militar com barra', '{ombros,triceps}'::text[], 'Barra', 'Em pé ou sentado, empurre a barra acima da cabeça a partir da altura dos ombros.', null),
  ('Elevação lateral com halteres', '{ombros}'::text[], 'Halteres', 'Eleve os braços lateralmente até a altura dos ombros e desça com controle.', null),
  ('Elevação frontal com halteres', '{ombros}'::text[], 'Halteres', 'Eleve os braços à frente até a altura dos ombros e desça com controle.', null),
  ('Crucifixo inverso com halteres', '{ombros,trapezio}'::text[], 'Halteres', 'Tronco inclinado à frente, abra os braços lateralmente aproximando as escápulas.', null),
  ('Face pull na polia', '{ombros,trapezio}'::text[], 'Polia com corda', 'Puxe a corda em direção ao rosto afastando as mãos e girando os ombros para fora.', null),
  ('Encolhimento com halteres', '{trapezio}'::text[], 'Halteres', 'Com os braços estendidos, eleve os ombros em direção às orelhas e desça.', null),
  ('Rosca direta com barra', '{biceps}'::text[], 'Barra', 'Com cotovelos junto ao corpo, flexione os cotovelos elevando a barra e desça com controle.', null),
  ('Rosca alternada com halteres', '{biceps}'::text[], 'Halteres', 'Flexione um cotovelo de cada vez girando o punho para cima durante a subida.', null),
  ('Rosca martelo', '{biceps,antebracos}'::text[], 'Halteres', 'Com as palmas voltadas uma para a outra, flexione os cotovelos e desça com controle.', null),
  ('Tríceps na polia', '{triceps}'::text[], 'Polia alta', 'Cotovelos junto ao corpo, estenda os cotovelos empurrando a barra ou corda para baixo.', null),
  ('Tríceps francês com halter', '{triceps}'::text[], 'Halter', 'Com o halter acima da cabeça, flexione os cotovelos levando-o para trás e estenda.', null),
  ('Tríceps no banco', '{triceps,peitoral}'::text[], 'Banco', 'Mãos apoiadas no banco atrás do corpo, flexione os cotovelos descendo o quadril e suba.', null),
  ('Prancha frontal', '{abdomen}'::text[], 'Peso corporal', 'Apoiado nos antebraços e pontas dos pés, mantenha o corpo alinhado pelo tempo indicado.', null),
  ('Prancha lateral', '{abdomen}'::text[], 'Peso corporal', 'Apoiado em um antebraço e na lateral do pé, mantenha o quadril elevado e alinhado.', null),
  ('Abdominal supra', '{abdomen}'::text[], 'Peso corporal', 'Deitado com joelhos flexionados, eleve os ombros do chão contraindo o abdômen.', null),
  ('Elevação de pernas deitado', '{abdomen}'::text[], 'Peso corporal', 'Deitado, eleve as pernas estendidas ou semiflexionadas e desça com controle.', null),
  ('Dead bug', '{abdomen}'::text[], 'Peso corporal', 'Deitado com braços e pernas elevados, estenda braço e perna opostos mantendo a lombar apoiada.', null),
  ('Bird dog', '{abdomen,lombar,gluteos}'::text[], 'Peso corporal', 'Em quatro apoios, estenda braço e perna opostos mantendo o tronco estável.', null),
  ('Extensão lombar no banco romano', '{lombar,gluteos,posteriores}'::text[], 'Banco romano', 'Com o quadril apoiado, flexione o tronco à frente e retorne até alinhar com as pernas.', null),
  ('Kettlebell swing', '{gluteos,posteriores,corpo_inteiro}'::text[], 'Kettlebell', 'Com movimento de quadril, balance o kettlebell até a altura do peito mantendo a coluna neutra.', null),
  ('Pallof press', '{abdomen}'::text[], 'Polia ou elástico', 'De lado para a polia, empurre as mãos à frente resistindo à rotação do tronco.', null),
  ('Step-up no banco', '{quadriceps,gluteos}'::text[], 'Banco ou caixa', 'Suba no banco apoiando um pé de cada vez e desça com controle.', null),
  ('Burpee', '{corpo_inteiro}'::text[], 'Peso corporal', 'Agache, leve os pés para trás em prancha, retorne e salte.', null);
