// Conteúdo dos Guias (2.10 Fase B), transcrito dos documentos aprovados em docs/conhecimento/ (revisão clínica do
// dono, 25/09/2026). Os .md são a fonte: ao revisar um documento, atualize o Guia correspondente aqui.
// Não contém dados de alunos. Na UI: catálogo de condições (qualquer staff) e montador (só nível completo de saúde).
import type { Guide } from "./types";

export const GUIDES: Record<string, Guide> = {
  lombar: {
    key: "lombar",
    title: "Lombalgia inespecífica",
    source: "lombalgia-inespecifica.md",
    summary: [
      "**Mantenha o aluno ativo:** exercício é tratamento de primeira linha na dor crônica; nenhum tipo é claramente superior — escolha o que ele gosta e consegue manter.",
      "**Adapte, não proíba:** sem alerta automático; se um exercício reproduzir sintomas, ajuste amplitude, carga, apoio, cadência, posição e volume. Nenhum exercício a evitar por padrão.",
      "**Guie-se pelos sintomas, não pelo laudo:** achados de imagem são comuns em pessoas sem dor.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual no dia seguinte → siga/progrida; acima disso → reduza.",
      "**Progrida aos poucos:** 2–10% de carga quando sobrarem 1–2 repetições além do alvo.",
      "**Sinais de alerta** (bexiga/intestino, dormência na \"sela\", fraqueza que piora, câncer, febre, perda de peso, trauma) → pare e encaminhe.",
      "**Fale de forma positiva:** \"sua coluna é forte e se adapta\"; evite \"desgaste\", \"coluna frágil\".",
    ],
    tables: [
      {
        title: "Alavancas de adaptação",
        kind: "guide",
        columns: ["Alavanca", "Como aplicar", "Nível", "Referência"],
        rows: [
          ["Amplitude", "Reduzir a amplitude à faixa sem piora e ampliar aos poucos (ex.: agachar até uma caixa).", "consenso", "prática clínica"],
          ["Carga", "Reduzir a carga e progredir 2–10% conforme tolerância.", "consenso", "[R17] (extrapolado)"],
          ["Apoio", "Acrescentar apoio (banco, parede, máquina) para diminuir a exigência de estabilização.", "consenso", "prática clínica"],
          ["Cadência", "Execução controlada; evitar rebotes e movimentos balísticos enquanto houver piora.", "consenso", "prática clínica"],
          ["Posição", "Trocar a variação (ex.: em pé → apoiado; carga axial → carga à frente).", "consenso", "prática clínica"],
          ["Volume", "Menos séries/repetições na crise; retomar gradualmente.", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Exemplos da biblioteca (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Levantamento terra / Levantamento terra romeno", "Se reproduzir sintomas ou gerar receio", "Barra elevada (blocos/rack), menor amplitude e carga; progredir conforme tolerância", "consenso", "prática clínica"],
          ["Agachamento livre com barra", "Se reproduzir sintomas", "Agachamento goblet ou até a caixa; reduzir profundidade/carga", "consenso", "prática clínica"],
          ["Remada curvada com barra", "Se reproduzir sintomas (tronco inclinado sustentado sob carga)", "Remada unilateral com halter apoiada no banco ou remada baixa na polia", "consenso", "prática clínica"],
          ["Kettlebell swing", "Fase de crise", "Reduzir carga e ritmo; trocar temporariamente por elevação pélvica", "consenso", "prática clínica"],
          ["Burpee", "Fase de crise", "Versão sem salto e mais lenta, ou retirar temporariamente", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** preferir **adaptar** a proibir. Não há base para restringir um exercício só pelo diagnóstico: por exemplo, flexão lombar maior ao levantar peso **não** se mostrou fator de risco para início/persistência da dor (evidência de baixa qualidade) [R13] **[fraca]**, e os eventos adversos do exercício foram majoritariamente leves (ex.: dor muscular) [R6] **[moderada]**. A adaptação é guiada pelo **comportamento dos sintomas daquele aluno**.",
      "**Levantamento terra pode fazer parte do tratamento.** Em ensaio clínico com 70 pessoas com dor lombar recorrente de padrão mecânico, um programa de levantamento terra com carga alta + educação sobre dor melhorou dor, força e resistência dentro do grupo; o controle motor de baixa carga foi superior em atividade e controle do movimento, mas não em dor [R26]. No seguimento de 24 meses, não houve diferença entre os grupos, e 50–80% dos participantes relataram menos dor e incapacidade [R27]. **[fraca]** (um ensaio pequeno) — base para **não** evitar o exercício por padrão; a escolha depende da preferência e da tolerância do aluno.",
      "**Extensão lombar: fortalecer os extensores é útil.** Treino resistido de extensão lombar trouxe melhora de dor e incapacidade na lombalgia crônica, em revisão não sistemática [R28] **[fraca]**; treino resistido está entre as modalidades mais eficazes em meta-análise em rede (qualidade baixa) [R8] **[fraca]**. Por isso a extensão lombar **não** tem cautela na lombalgia inespecífica — só em quem tem **intolerância à extensão** (condição por padrão).",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia (suspeita de síndrome da cauda equina) [R19]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino** (ex.: dificuldade para urinar, perda de controle).",
        "**Dormência ou formigamento na região da \"sela\"** (nádegas, parte interna das coxas, região genital) (baixo).",
        "Dor irradiada para **uma ou as duas pernas** com perda de sensibilidade ou **fraqueza** que está **piorando**.",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino [R19; R1 — 1.1.1] (o modelo usa \"referenciação urgente\", em até 5 dias, conforme o grau de suspeita)", tone: "refer", items: [
        "**História de câncer** (ex.: mama, próstata, pulmão, rim, tireoide) (baixo).",
        "**Perda de peso sem explicação** (mais de 5% em 6 meses) (alta).",
        "**Febre** junto da dor (baixo); **imunossupressão** (ex.: diabetes, HIV, artrite reumatoide, infecção prévia, consumo excessivo de álcool, uso prolongado de corticoide) — suspeita de infecção (baixo).",
        "Suspeita de **fratura**: trauma importante (ex.: queda de 5 degraus ou de 90 cm) (elevado); mudança súbita de postura com aumento da dor em quem tem osteoporose conhecida (baixo); uso prévio de corticoide (> 5 mg por 3 meses).",
        "**Dor noturna** que impede voltar a dormir e obriga a levantar; piora progressiva, dor em faixa, incapacidade de ficar deitado (baixo).",
        "Suspeita de doença inflamatória (ex.: espondiloartrite) [R1 — 1.1.1].",
      ] },
    ],
    avoidWords: ["desgaste", "coluna degenerada", "disco saiu do lugar", "coluna frágil/instável", "nunca dobre as costas", "isso vai piorar sua hérnia"],
    phrases: [
      "\"Sua coluna é forte e se adapta ao treino. Vamos aumentar aos poucos.\"",
      "\"Movimento ajuda na recuperação. Mantenha suas atividades do dia a dia.\"",
      "\"Um pouco de desconforto durante o exercício pode acontecer. Se passar de 5/10 ou não voltar ao normal até amanhã, me avise para ajustarmos.\"",
      "\"Hoje faremos este exercício com menos amplitude; vamos ampliar conforme você se sentir bem.\"",
      "\"Achados em exames são comuns em pessoas sem dor. O que guia o treino é como você se sente.\"",
      "\"Na crise, prefira se movimentar dentro do confortável em vez de ficar parado.\"",
    ],
    references: [
      { id: "R1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "R6", text: "Hayden JA, Ellis J, Ogilvie R, Malmivaara A, van Tulder MW. Exercise therapy for chronic low back pain. Cochrane Database Syst Rev. 2021;CD009790.", url: "https://doi.org/10.1002/14651858.CD009790.pub2" },
      { id: "R8", text: "Owen PJ, Miller CT, Mundell NL, Verswijveren SJJM, Tagliaferri SD, Brisby H, et al. Which specific modes of exercise training are most effective for treating low back pain? Network meta-analysis. Br J Sports Med. 2020;54(21):1279-1287.", url: "https://doi.org/10.1136/bjsports-2019-100886" },
      { id: "R13", text: "Saraceni N, Kent P, Ng L, Campbell A, Straker L, O'Sullivan P. To Flex or Not to Flex? Is There a Relationship Between Lumbar Spine Flexion During Lifting and Low Back Pain? A Systematic Review With Meta-analysis. J Orthop Sports Phys Ther. 2020;50(3):121-130.", url: "https://doi.org/10.2519/jospt.2020.9218" },
      { id: "R17", text: "American College of Sports Medicine. Progression Models in Resistance Training for Healthy Adults (position stand). Med Sci Sports Exerc. 2009;41(3):687-708.", url: "https://doi.org/10.1249/MSS.0b013e3181915670" },
      { id: "R19", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
      { id: "R26", text: "Aasa B, Berglund L, Michaelson P, Aasa U. Individualized Low-Load Motor Control Exercises and Education Versus a High-Load Lifting Exercise and Education to Improve Activity, Pain Intensity, and Physical Performance in Patients With Low Back Pain: A Randomized Controlled Trial. J Orthop Sports Phys Ther. 2015;45(2):77-85.", url: "https://doi.org/10.2519/jospt.2015.5021" },
      { id: "R27", text: "Michaelson P, Holmberg D, Aasa B, Aasa U. High load lifting exercise and low load motor control exercises as interventions for patients with mechanical low back pain: A randomized controlled trial with 24-month follow-up. J Rehabil Med. 2016;48(5):456-463.", url: "https://doi.org/10.2340/16501977-2091" },
      { id: "R28", text: "Steele J, Bruce-Low S, Smith D. A Review of the Clinical Value of Isolated Lumbar Extension Resistance Training for Chronic Low Back Pain. PM&R. 2015;7(2):169-187.", url: "https://doi.org/10.1016/j.pmrj.2014.10.009" },
    ],
  },
  cervical: {
    key: "cervical",
    title: "Cervicalgia (dor no pescoço inespecífica)",
    source: "cervicalgia.md",
    summary: [
      "**Bom prognóstico:** a dor no pescoço costuma ter curso benigno; tranquilize e mantenha o aluno ativo.",
      "**Fortaleça pescoço, escápulas e ombros:** força e resistência dessa região ajudam (só alongar, não); pouco já ajuda (2 min/dia em ensaio clínico) e nenhum tipo é claramente superior — escolha o que o aluno mantém.",
      "**Adapte se reproduzir sintomas:** amplitude, carga e posição da cabeça (sem projetar o queixo, sem puxar a nuca).",
      "**Observe o braço:** dor que recua do braço para o pescoço é bom sinal; dor que desce mais no braço → ajuste o treino; **perda de força ou dormência que piora → encaminhe** (não é ajuste de treino).",
      "**Emergência:** cefaleia súbita e intensa, tontura, fala enrolada, visão dupla, dificuldade para engolir, desequilíbrio → **interrompa e acione o SAMU (192) / pronto-socorro**.",
      "**Fale de forma positiva:** \"seu pescoço é forte e vamos fortalecê-lo\"; evite \"bico de papagaio\", \"coluna gasta\".",
    ],
    tables: [
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Abdominal supra", "Se puxar a cabeça/nuca com as mãos", "Mãos no peito ou apoio da cabeça; ou dead bug/prancha", "consenso", "prática clínica"],
          ["Encolhimento com halteres", "Se reproduzir sintomas", "Carga menor, sem rolar os ombros; manter o queixo recolhido", "consenso", "prática clínica"],
          ["Desenvolvimento militar com barra / Desenvolvimento com halteres / Tríceps francês com halter", "Se a elevação acima da cabeça ou a posição da cabeça reproduzir sintomas", "Amplitude menor; halteres com pegada neutra; cabeça neutra, sem projetar o queixo", "consenso", "prática clínica"],
          ["Barra fixa / Puxada frontal na polia", "Se projetar o pescoço para alcançar a barra", "Amplitude até a altura do queixo sem projetar a cabeça; carga assistida", "consenso", "prática clínica"],
          ["Prancha frontal / Flexão de braços", "Se a cabeça \"cair\" ou estender", "Cabeça alinhada com o tronco; apoio nos joelhos; tempo menor", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Costumam ajudar** (sem alerta): exercícios resistidos para escápulas e ombros — face pull na polia, crucifixo inverso, remadas, elevação lateral até a altura do ombro [C1, C5, C6]. **[fraca]** (as referências apoiam fortalecimento da região cervical/escapular/ombro, não exercícios específicos da biblioteca)",
    ],
    redFlags: [
      { title: "Emergência imediata — interromper o treino e acionar o SAMU (192) / pronto-socorro [sinais: C8; conduta: consenso]", tone: "emergency", items: [
        "**Cefaleia súbita e intensa (\"em trovoada\")**, ou dor de cabeça/pescoço descrita como **incomum** e que **piora progressivamente**, sobretudo após trauma (caso típico de dissecção no modelo; cefaleia em 81% e dor no pescoço em 57–80% das dissecções).",
        "**Instabilidade/desequilíbrio** (67% nas dissecções vertebrobasilares), **fala enrolada ou dificuldade para falar** (44%), **fraqueza** nos braços ou pernas, **dificuldade para engolir**, **náusea/vômito**, **paralisia facial**, **pálpebra caída**, **tontura**, **alteração visual** (visão dupla, perda de visão), perda de consciência, confusão.",
        "**Formigamento** na face, nos braços ou nas pernas junto com os sinais acima.",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino [C9; C4 — rec. 1 e 3]", tone: "refer", items: [
        "**Trauma importante** recente (queda, acidente) com dor no pescoço — excluir lesão estrutural antes de classificar como dor inespecífica.",
        "**Sintomas neurológicos nos dois lados** (braços e/ou pernas), **alteração da marcha** ou **da coordenação** [C9].",
        "**Perda de força ou dormência progressiva** no braço.",
        "Sinais gerais (câncer, perda de peso sem explicação, febre, imunossupressão, dor noturna que impede dormir) ou **sintomas novos ou que pioram**.",
      ] },
    ],
    avoidWords: ["bico de papagaio", "coluna gasta", "retificação grave", "pescoço frágil", "não pode fazer força com o pescoço"],
    phrases: [
      "\"Dor no pescoço costuma melhorar; manter-se ativo ajuda.\"",
      "\"Vamos fortalecer pescoço, costas e ombros aos poucos — poucos minutos por dia já fazem diferença.\"",
      "\"Neste exercício, mantenha o queixo recolhido e a cabeça alinhada.\"",
      "\"Se a dor ou o formigamento descerem para o braço, me avise para ajustarmos.\"",
      "\"Achados como abaulamento aparecem em muita gente sem dor; o que guia o treino é como você se sente.\"",
    ],
    references: [
      { id: "C1", text: "Gross A, Kay TM, Paquin JP, Blanchette S, Lalonde P, Christie T, et al. Exercises for mechanical neck disorders. Cochrane Database Syst Rev. 2015;CD004250.", url: "https://doi.org/10.1002/14651858.CD004250.pub5" },
      { id: "C4", text: "Côté P, Wong JJ, Sutton D, Shearer HM, Mior S, Randhawa K, et al. Management of neck pain and associated disorders: A clinical practice guideline from the Ontario Protocol for Traffic Injury Management (OPTIMa) Collaboration. Eur Spine J. 2016;25(7):2000-2022.", url: "https://doi.org/10.1007/s00586-016-4467-7" },
      { id: "C5", text: "Andersen LL, Kjær M, Søgaard K, Hansen L, Kryger AI, Sjøgaard G. Effect of two contrasting types of physical exercise on chronic neck muscle pain. Arthritis Care Res. 2008;59(1):84-91.", url: "https://doi.org/10.1002/art.23256" },
      { id: "C6", text: "Andersen LL, Saervoll CA, Mortensen OS, Poulsen OM, Hannerz H, Zebis MK. Effectiveness of small daily amounts of progressive resistance training for frequent neck/shoulder pain: Randomised controlled trial. Pain. 2011;152(2):440-446.", url: "https://doi.org/10.1016/j.pain.2010.11.016" },
      { id: "C8", text: "Rushton A, Carlesso LC, Flynn T, Hing WA, Rubinstein SM, Vogel S, et al. International Framework for Examination of the Cervical Region for Potential of Vascular Pathologies of the Neck Prior to Musculoskeletal Intervention: International IFOMPT Cervical Framework. J Orthop Sports Phys Ther. 2023;53(1):7-22.", url: "https://doi.org/10.2519/jospt.2022.11147" },
      { id: "C9", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
  hernia_lombar_flexao: {
    key: "hernia_lombar_flexao",
    title: "Hérnia discal lombar (intolerância à flexão)",
    source: "hernia-discal-lombar-flexao.md",
    summary: [
      "**Bom prognóstico:** muitas hérnias diminuem sozinhas e a maioria das pessoas melhora sem cirurgia; mantenha o aluno ativo.",
      "**Guie-se pelos sintomas:** nesta condição, flexão da coluna (e ficar sentado) costuma piorar; ajuste pelo que o aluno sente.",
      "**Observe a perna:** dor que recua da perna para a lombar é bom sinal; dor que desce mais na perna → ajuste o treino; **perda de força ou dormência que piora → encaminhe** (não é ajuste de treino).",
      "**Adapte a flexão com carga:** carga junto ao corpo, amplitude até onde não há sintomas, variações apoiadas; troque abdominais em flexão por isometrias.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual até o dia seguinte → siga; acima disso → reduza.",
      "**Sinais de alerta:** alteração de bexiga/intestino, dormência na \"sela\", fraqueza na perna que piora, sintomas nas duas pernas → pare e encaminhe **no mesmo dia**.",
      "**Fale de forma positiva:** \"o corpo consegue reabsorver parte da hérnia\"; evite \"disco saiu do lugar\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Abdominal supra", "Flexão lombar repetida", "Isometrias: dead bug, prancha, Pallof press", "consenso", "prática clínica"],
          ["Elevação de pernas deitado", "Tende a levar a lombar à flexão no fim da amplitude", "Joelhos flexionados, amplitude menor sem tirar a lombar do apoio, ou dead bug", "consenso", "prática clínica"],
          ["Levantamento terra / Levantamento terra romeno", "Flexão sob carga; pressão no disco maior com costas curvadas e carga longe do corpo", "Barra elevada (blocos/rack), carga junto ao corpo, amplitude até onde não há sintomas; progredir conforme tolerância", "fraca (mecanismo)", "[H14] + prática clínica"],
          ["Remada curvada com barra", "Tronco inclinado sustentado sob carga", "Remada unilateral apoiada no banco ou remada baixa na polia com tronco ereto", "fraca (mecanismo)", "[H14] + prática clínica"],
          ["Leg press 45°", "No fundo do movimento a pelve pode \"enrolar\" (flexão lombar sob carga)", "Limitar a amplitude antes da retroversão da pelve", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Agachamento livre com barra", "Se reproduzir sintomas (flexão lombar no fundo)", "Agachar até uma caixa na altura sem sintomas; agachamento goblet", "consenso", "prática clínica"],
          ["Kettlebell swing", "Fase de crise", "Reduzir carga e ritmo; trocar temporariamente por elevação pélvica", "consenso", "prática clínica"],
          ["Burpee", "Fase de crise", "Versão sem salto e mais lenta, ou retirar temporariamente", "consenso", "prática clínica"],
          ["Elevação pélvica", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Ponte de glúteos", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir. Nesta condição a cautela é **direcional**: exercícios com flexão lombar sob carga, repetida ou sustentada. O alerta não bloqueia o treino; lembra o professor de ajustar. A mesma tabela vale para **\"Dor lombar — intolerância à flexão\"** (sem laudo).",
      "**Costumam ser bem tolerados** (sem alerta; confirmar pelos sintomas): ponte de glúteos e elevação pélvica (com a técnica acima), bird dog, prancha frontal e lateral, Pallof press, caminhada. **[consenso]** — prática clínica.",
      "**Horário:** evitar concentrar exercícios de flexão lombar logo após acordar [H15]. **[fraca]** (extrapolado)",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia [H17]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino** (ex.: dificuldade para urinar, perda de controle).",
        "**Dormência ou formigamento na região da \"sela\"** (nádegas, parte interna das coxas, região genital) (baixo).",
        "Dor, dormência ou **fraqueza** nas pernas que está **piorando**, especialmente **nas duas pernas**.",
      ] },
      { title: "Encaminhar para reavaliação [H17; H1 — 1.1.1]", tone: "refer", items: [
        "**Perda de força ou dormência progressiva** na perna (mesmo sem os sinais de emergência acima) — encaminhamento, não ajuste de treino.",
        "Dor na perna que continua **descendo** apesar dos ajustes.",
        "Qualquer sinal de alerta geral (câncer, perda de peso sem explicação, febre, imunossupressão, trauma, dor noturna que impede dormir) ou sintomas **novos ou diferentes**.",
      ] },
    ],
    avoidWords: ["disco saiu do lugar", "hérnia vai estourar", "coluna travada", "nunca mais levante peso", "você não pode dobrar as costas"],
    phrases: [
      "\"Hérnias de disco costumam melhorar com o tempo; o corpo consegue reabsorver parte dela.\"",
      "\"Vamos fazer este exercício na amplitude em que você se sente bem e ampliar aos poucos.\"",
      "\"Se a dor descer mais para a perna ou aparecer formigamento, me avise para ajustarmos.\"",
      "\"Mantenha-se em movimento: caminhar costuma ajudar.\"",
      "\"Evite ficar muito tempo sentado; levante e movimente-se a cada pouco.\" (prática clínica)",
      "\"Achados em exames são comuns em pessoas sem dor; o que guia o treino é como você se sente.\"",
    ],
    references: [
      { id: "H1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "H14", text: "Wilke H, Neef P, Caimi M, Hoogland T, Claes LE. New In Vivo Measurements of Pressures in the Intervertebral Disc in Daily Life. Spine. 1999;24(8):755-762.", url: "https://doi.org/10.1097/00007632-199904150-00005" },
      { id: "H15", text: "Snook SH, Webster BS, McGorry RW, Fogleman MT, McCann KB. The Reduction of Chronic Nonspecific Low Back Pain Through the Control of Early Morning Lumbar Flexion. Spine. 1998;23(23):2601-2607.", url: "https://doi.org/10.1097/00007632-199812010-00015" },
      { id: "H17", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
  estenose_lombar_extensao: {
    key: "estenose_lombar_extensao",
    title: "Estenose lombar (intolerância à extensão)",
    source: "estenose-lombar-extensao.md",
    summary: [
      "**Padrão típico:** dor nas costas/pernas que piora em pé parado, andando ou com a coluna em extensão e melhora sentado ou inclinado para a frente.",
      "**Exercício ajuda:** programas com exercício (supervisionados e individualizados) melhoram sintomas, função e caminhada; em ensaio clínico, fisioterapia teve resultado semelhante à cirurgia em 2 anos.",
      "**Prefira posições em flexão leve:** bicicleta ergométrica, exercícios sentados ou apoiados; caminhada em intervalos, com pausas sentado.",
      "**Adapte a extensão:** evite arquear a lombar (desenvolvimento em pé, extensão lombar além do neutro); na ponte e na elevação pélvica, termine com retroversão da pelve.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual até o dia seguinte → siga; acima disso → reduza.",
      "**Sinais de alerta:** alteração de bexiga/intestino, dormência na \"sela\", fraqueza ou dormência nas pernas que piora → pare e encaminhe.",
      "**Fale de forma positiva:** \"vamos achar as posições em que você anda e treina melhor\"; evite \"coluna apertada/estrangulada\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Extensão lombar no banco romano", "Extensão lombar repetida", "Amplitude só até o neutro, sem hiperextensão; ou bird dog", "fraca (mecanismo)", "[E5] + prática clínica"],
          ["Desenvolvimento militar com barra", "Em pé com carga acima da cabeça, tendência a arquear a lombar", "Sentado com apoio nas costas, ou halteres/landmine, sem arquear a lombar", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Elevação pélvica", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Ponte de glúteos", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Pullover com halter", "Se arquear a lombar no alongamento", "Amplitude menor; lombar apoiada no banco", "consenso", "prática clínica"],
          ["Prancha frontal", "Se o quadril \"cair\" (lombar em extensão)", "Apoio nos joelhos; tempo menor", "consenso", "prática clínica"],
          ["Agachamento búlgaro / Afundo com halteres", "Se a perna de trás levar a lombar à extensão", "Passada menor; tronco levemente inclinado à frente", "consenso", "prática clínica"],
          ["Levantamento terra", "Se \"passar do ponto\" no fim (hiperextensão)", "Terminar com quadril e tronco alinhados", "consenso", "prática clínica"],
          ["Exercícios longos em pé", "Sintomas ao ficar em pé", "Intercalar com pausas sentado; versões sentadas", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir. Nesta condição a cautela é **direcional**: exercícios que levam a lombar à **extensão** (arquear), sob carga ou sustentada, e ficar muito tempo em pé. O alerta não bloqueia o treino.",
      "**Costumam ser bem tolerados** (sem alerta; confirmar pelos sintomas): bicicleta ergométrica [E9, E10], exercícios em flexão [E10], leg press 45°, exercícios sentados ou apoiados, remadas sentadas, caminhada em intervalos. **[consenso]** (as referências indicam uso nos programas testados, não superioridade).",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia [E11]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino**.",
        "**Dormência ou formigamento na região da \"sela\"** (nádegas, parte interna das coxas, região genital) (baixo).",
        "**Fraqueza** nas pernas que piora rapidamente, ou sintomas novos nas **duas pernas**.",
      ] },
      { title: "Encaminhar para reavaliação [E11; E1 — 1.1.1]", tone: "refer", items: [
        "**Perda de força ou dormência progressivas** ao longo de semanas — encaminhamento, não ajuste de treino.",
        "**Piora progressiva da distância de caminhada com fraqueza ou dormência** nas pernas.",
        "Sinais de alerta gerais (história de câncer, perda de peso sem explicação, febre, trauma, dor noturna que impede dormir) ou sintomas **novos ou diferentes**.",
      ] },
    ],
    avoidWords: ["coluna apertada", "nervo estrangulado", "canal fechando", "vai precisar operar", "não pode ficar em pé"],
    phrases: [
      "\"Vamos encontrar as posições em que você se sente melhor para andar e treinar.\"",
      "\"Caminhe em intervalos: quando as pernas pesarem, sente um pouco e siga depois.\"",
      "\"Na bicicleta você costuma render mais; vamos usá-la para ganhar fôlego.\"",
      "\"Neste exercício, pare quando o quadril alinhar com o tronco, sem arquear as costas.\"",
      "\"Se a força ou a sensibilidade nas pernas mudarem, me avise na hora.\"",
      "\"Muitas pessoas com esse diagnóstico melhoram com exercício; vamos progredir aos poucos.\"",
    ],
    references: [
      { id: "E1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "E5", text: "Schmid MR, Stucki G, Duewell S, Wildermuth S, Romanowski B, Hodler J. Changes in cross-sectional measurements of the spinal canal and intervertebral foramina as a function of body position: in vivo studies on an open-configuration MR system. AJR Am J Roentgenol. 1999;172(4):1095-1102.", url: "https://doi.org/10.2214/ajr.172.4.10587155" },
      { id: "E9", text: "Minetama M, Kawakami M, Teraguchi M, Kagotani R, Mera Y, Sumiya T, et al. Supervised physical therapy vs. home exercise for patients with lumbar spinal stenosis: a randomized controlled trial. Spine J. 2019;19(8):1310-1318.", url: "https://doi.org/10.1016/j.spinee.2019.04.009" },
      { id: "E10", text: "Pua YH, Cai CC, Lim KC. Treadmill walking with body weight support is no more effective than cycling when added to an exercise program for lumbar spinal stenosis: a randomised controlled trial. Aust J Physiother. 2007;53(2):83-89.", url: "https://doi.org/10.1016/S0004-9514(07)70040-5" },
      { id: "E11", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
  espondilolistese_extensao: {
    key: "espondilolistese_extensao",
    title: "Espondilolistese (intolerância à extensão)",
    source: "espondilolistese-extensao.md",
    summary: [
      "**Achado comum:** espondilólise e espondilolistese aparecem com frequência em exames de pessoas sem dor; o que orienta o treino são os sintomas.",
      "**Exercício é a base:** estabilização específica (abdominais profundos + multífidos) e exercícios em flexão tiveram bons resultados; nenhum programa é claramente superior.",
      "**Adapte a extensão:** nesta condição, arquear a lombar costuma piorar — limite a amplitude em extensão e prefira variações apoiadas.",
      "**Integre a estabilização** às posições e tarefas que antes incomodavam, progredindo aos poucos.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual até o dia seguinte → siga; acima disso → reduza.",
      "**Sinais de alerta:** alteração de bexiga/intestino, dormência na \"sela\", perda de força ou dormência progressiva nas pernas → pare e encaminhe.",
      "**Fale de forma positiva:** \"sua coluna é estável e vamos fortalecê-la\"; evite \"vértebra solta\", \"coluna escorregando\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Extensão lombar no banco romano", "Extensão lombar repetida", "Amplitude só até o neutro, sem hiperextensão; ou bird dog", "fraca (mecanismo)", "[S8] + prática clínica"],
          ["Desenvolvimento militar com barra", "Em pé com carga acima da cabeça, tendência a arquear a lombar", "Sentado com apoio nas costas, ou halteres/landmine, sem arquear a lombar", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Elevação pélvica", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Ponte de glúteos", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Pullover com halter", "Se arquear a lombar no alongamento", "Amplitude menor; lombar apoiada no banco", "consenso", "prática clínica"],
          ["Prancha frontal", "Se o quadril \"cair\" (lombar em extensão)", "Apoio nos joelhos; tempo menor", "consenso", "prática clínica"],
          ["Agachamento búlgaro / Afundo com halteres", "Se a perna de trás levar a lombar à extensão", "Passada menor; tronco levemente inclinado à frente", "consenso", "prática clínica"],
          ["Levantamento terra", "Se \"passar do ponto\" no fim (hiperextensão)", "Terminar com quadril e tronco alinhados", "consenso", "prática clínica"],
          ["Kettlebell swing", "Se arquear a lombar no fim do movimento", "Terminar com quadril e tronco alinhados; reduzir carga", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir. A cautela é **direcional** (extensão lombar sob carga, repetida ou sustentada) e usa a **mesma tabela de alertas** da estenose.",
      "**Costumam ser bem tolerados** (sem alerta; confirmar pelos sintomas): exercícios de estabilização (dead bug, bird dog, prancha lateral, Pallof press) [S3], exercícios em flexão [S4], bicicleta ergométrica, exercícios sentados ou apoiados. **[consenso]** (as referências indicam uso nos programas testados, não superioridade).",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia [S9]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino**.",
        "**Dormência ou formigamento na região da \"sela\"** (baixo).",
        "**Fraqueza** nas pernas que piora rapidamente, ou sintomas novos nas **duas pernas**.",
      ] },
      { title: "Encaminhar para reavaliação [S9; S1 — 1.1.1]", tone: "refer", items: [
        "**Perda de força ou dormência progressiva** nas pernas — encaminhamento, não ajuste de treino.",
        "**Piora progressiva** da dor ou da capacidade de andar apesar dos ajustes.",
        "Sinais de alerta gerais (história de câncer, perda de peso sem explicação, febre, trauma, dor noturna que impede dormir) ou sintomas **novos ou diferentes**.",
      ] },
    ],
    avoidWords: ["vértebra solta", "coluna escorregando", "coluna instável", "pode travar a qualquer momento", "nunca mais faça extensão"],
    phrases: [
      "\"Esse achado é comum em exames de pessoas sem dor; o que guia o treino é como você se sente.\"",
      "\"Vamos fortalecer o abdômen e as costas para você se sentir firme nas tarefas do dia a dia.\"",
      "\"Neste exercício, pare quando o quadril alinhar com o tronco, sem arquear as costas.\"",
      "\"Se algum movimento para trás incomodar, me avise; temos outras formas de treinar o mesmo músculo.\"",
      "\"Se a força ou a sensibilidade nas pernas mudarem, me avise na hora.\"",
    ],
    references: [
      { id: "S1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "S3", text: "O'Sullivan PB, Phyty GDM, Twomey LT, Allison GT. Evaluation of Specific Stabilizing Exercise in the Treatment of Chronic Low Back Pain With Radiologic Diagnosis of Spondylolysis or Spondylolisthesis. Spine. 1997;22(24):2959-2967.", url: "https://doi.org/10.1097/00007632-199712150-00020" },
      { id: "S4", text: "Nava-Bringas TI, Romero-Fierro LO, Trani-Chagoya YP, Macías-Hernández SI, García-Guerrero E, Hernández-López M, et al. Stabilization Exercises Versus Flexion Exercises in Degenerative Spondylolisthesis: A Randomized Controlled Trial. Phys Ther. 2021;101(8):pzab108.", url: "https://doi.org/10.1093/ptj/pzab108" },
      { id: "S8", text: "Schmid MR, Stucki G, Duewell S, Wildermuth S, Romanowski B, Hodler J. Changes in cross-sectional measurements of the spinal canal and intervertebral foramina as a function of body position: in vivo studies on an open-configuration MR system. AJR Am J Roentgenol. 1999;172(4):1095-1102.", url: "https://doi.org/10.2214/ajr.172.4.10587155" },
      { id: "S9", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
  ombro_manguito: {
    key: "ombro_manguito",
    title: "Dor no ombro relacionada ao manguito rotador",
    source: "ombro-manguito.md",
    summary: [
      "**Exercício é o tratamento de primeira linha;** a cirurgia de descompressão não mostrou benefício sobre a cirurgia simulada — o treino é parte central do cuidado.",
      "**Carregue o manguito aos poucos:** exercício progressivo aumenta a capacidade de carga; não há protocolo único comprovado.",
      "**Achados de imagem são comuns sem dor** e aumentam com a idade; guie-se pelos sintomas.",
      "**Adapte o que reproduz sintomas:** tríceps no banco → tríceps na polia ou francês; acima da cabeça, amplitude sem dor e no plano da escápula. Monitore: até 5/10 e de volta ao habitual até o dia seguinte → siga.",
      "**Emergência (192):** dor no ombro/braço com esforço + falta de ar, sudorese ou dor no peito.",
      "**Sinais de alerta:** suspeita de infecção na articulação, luxação, ruptura após trauma, suspeita de tumor, várias articulações inflamadas → pare e encaminhe.",
      "**Fale de forma positiva:** \"o tendão se adapta à carga\"; evite \"tendão rasgando\", \"osso raspando no tendão\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Tríceps no banco", "Peso do corpo com o ombro no fim da extensão", "Tríceps na polia ou francês com halter", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Desenvolvimento militar com barra", "Se a carga acima da cabeça reproduzir sintomas", "Amplitude sem dor, no plano da escápula; halteres com pegada neutra ou landmine press", "consenso", "[O1] (ergonomia) + prática clínica"],
          ["Elevação lateral com halteres", "Se a elevação acima do ombro reproduzir sintomas", "Amplitude sem dor, no plano da escápula (braço um pouco à frente), polegar para cima", "consenso", "[O1] (ergonomia) + prática clínica"],
          ["Desenvolvimento com halteres", "Se a elevação acima da cabeça doer", "Amplitude até a altura tolerada; pegada neutra", "consenso", "prática clínica"],
          ["Elevação frontal com halteres", "Se doer acima do ombro", "Até a altura do ombro", "consenso", "prática clínica"],
          ["Supino reto com barra / Supino reto e inclinado com halteres", "Se doer no fundo do movimento", "Pegada um pouco mais fechada, cotovelos mais junto ao corpo, amplitude menor", "consenso", "prática clínica"],
          ["Crucifixo com halteres / Crossover na polia", "Se doer no alongamento", "Amplitude menor (cotovelos na linha do tronco)", "consenso", "prática clínica"],
          ["Pullover com halter / Tríceps francês com halter", "Se doer com o braço acima da cabeça", "Amplitude menor; trocar por tríceps na polia", "consenso", "prática clínica"],
          ["Barra fixa / Puxada frontal na polia", "Se doer no alto", "Pegada neutra; amplitude menor; carga assistida", "consenso", "prática clínica"],
          ["Flexão de braços", "Se doer no fundo", "Mãos um pouco elevadas; amplitude menor", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir; o objetivo é **carregar** o manguito de forma progressiva, não poupá-lo.",
    ],
    redFlags: [
      { title: "Emergência imediata — interromper o treino e acionar o SAMU (192) / pronto-socorro [O12] [consenso] (diretriz de dor torácica)", tone: "emergency", items: [
        "**Dor no ombro ou no braço que aparece com o esforço** acompanhada de **falta de ar, sudorese ou dor/aperto no peito**. A diretriz descreve a dor anginosa como desconforto no peito **ou no pescoço, ombros, mandíbula ou braços**, desencadeado pelo esforço e aliviado pelo repouso; dor no peito e/ou em outras áreas (ex.: braços, costas, mandíbula) por mais de 15 minutos, ou dor no peito com náusea/vômito, sudorese intensa ou falta de ar, pode indicar síndrome coronariana aguda, e a suspeita com dor atual leva a **encaminhamento de emergência** ao hospital [O12 — rec. 1.2.1.3, 1.2.1.7 e 1.3.3.1].",
      ] },
      { title: "Emergência — encaminhar no mesmo dia [O9]", tone: "sameDay", items: [
        "**Suspeita de infecção articular.**",
        "**Luxação não reduzida.**",
      ] },
      { title: "Encaminhar com urgência [O9]", tone: "refer", items: [
        "**Suspeita de tumor/malignidade** (ex.: história de câncer, perda de peso sem explicação, dor noturna intensa).",
        "**Ruptura aguda do manguito após trauma.**",
        "**Artrite inflamatória nova** (dor e inchaço em várias articulações).",
        "Tendinite calcária aguda (dor muito intensa) não é sinal de alerta, mas merece encaminhamento precoce para tratamento [O9].",
      ] },
    ],
    avoidWords: ["tendão rasgando", "osso raspando/cortando o tendão", "ombro gasto", "nunca mais levante o braço", "vai precisar operar"],
    phrases: [
      "\"O tendão se adapta à carga: vamos aumentar aos poucos.\"",
      "\"Um pouco de desconforto durante o exercício pode acontecer; se passar de 5/10 ou não voltar ao normal até amanhã, me avise para ajustarmos.\"",
      "\"Hoje vamos elevar o braço só até a altura do ombro; depois ampliamos.\"",
      "\"Achados no exame do ombro são comuns em pessoas sem dor; o que guia o treino é como você se sente.\"",
      "\"No dia a dia, faça pausas quando precisar trabalhar com os braços acima da cabeça.\"",
    ],
    references: [
      { id: "O1", text: "Lambers Heerspink FO, Veen EJD, Dorrestijn O, Visser CPJ, Leijs MJC, Van Poppel D, et al. Update of guideline for diagnosis and treatment of subacromial pain syndrome: a multidisciplinary review by the Dutch Orthopedic Association Part 1: preventive measures, diagnostics, and non-surgical treatment of subacromial pain syndrome. Acta Orthop. 2026;97.", url: "https://doi.org/10.2340/17453674.2026.45365" },
      { id: "O9", text: "Kulkarni R, Gibson J, Brownson P, Thomas M, Rangan A, Carr AJ, et al. Subacromial shoulder pain. Shoulder Elbow. 2015;7(2):135-143.", url: "https://doi.org/10.1177/1758573215576456" },
      { id: "O12", text: "National Institute for Health and Care Excellence (NICE). Recent-onset chest pain of suspected cardiac origin: assessment and diagnosis. Clinical guideline CG95. Publicada em 24/03/2010, atualizada em 30/11/2016.", url: "https://www.nice.org.uk/guidance/cg95/chapter/Recommendations" },
    ],
  },
  joelho_patelofemoral: {
    key: "joelho_patelofemoral",
    title: "Dor patelofemoral",
    source: "joelho-patelofemoral.md",
    summary: [
      "**Exercício é o tratamento de escolha:** fortaleça **quadril e joelho juntos** (melhor que só joelho).",
      "**Dose a carga, não pare:** reduza amplitude e volume do que dói (agachar fundo, escada, saltos, corrida) e volte a progredir; ajustar a atividade faz parte do tratamento.",
      "**Fase mais sensível:** agachamento e leg press de 0° a ~45° de flexão; cadeira extensora de 90° a ~45° (sem a extensão final) — progrida a amplitude conforme a dor permite (evidência fraca).",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual até o dia seguinte → siga; acima disso → reduza.",
      "**Sinais de alerta:** trauma com inchaço rápido, joelho quente e inchado, travamento, sensação de a patela \"sair\", panturrilha inchada e dolorida → pare e encaminhe.",
      "**Fale de forma positiva:** \"seu joelho aguenta carga e vai se adaptar\"; evite \"cartilagem gasta\", \"joelho fraco\".",
    ],
    tables: [
      {
        title: "Fase mais sensível (amplitudes de menor carga)",
        kind: "guide",
        columns: ["Exercício", "Por quê", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Cadeira extensora", "Estresse patelofemoral maior perto da extensão completa (0–30°)", "Amplitude de 90° a 45° de flexão (sem estender por completo) enquanto houver dor; ampliar com a melhora", "fraca", "[P8]"],
          ["Agachamento livre com barra", "Estresse patelofemoral maior no fundo (60–90°) com carga alta", "Amplitude de 0° a ~45°, ou até onde não reproduzir dor; goblet ou leg press com a mesma amplitude", "fraca", "[P8]"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Agachamento goblet / Leg press 45°", "Se doer no fundo", "Amplitude de 0° a ~45° ou sem dor; progredir a amplitude", "fraca", "[P8] (medido no agachamento; extrapolado)"],
          ["Afundo com halteres / Agachamento búlgaro", "Se doer no fundo", "Passo mais curto e amplitude menor; apoio para equilíbrio", "consenso", "prática clínica"],
          ["Step-up no banco", "Se doer ao subir ou descer", "Degrau mais baixo; descida controlada", "consenso", "prática clínica"],
          ["Burpee", "Se o salto ou o agachamento fundo doerem", "Sem salto; descer até onde não doer", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir; o objetivo é **carregar** quadril e joelho de forma progressiva.",
      "**Costumam ajudar** (sem alerta): fortalecimento de quadril — cadeira abdutora, elevação pélvica, ponte de glúteos, prancha lateral — combinado com quadríceps [P2, P3, P5]. **[moderada]** (as referências apoiam exercícios de quadril e joelho, não exercícios específicos da biblioteca)",
    ],
    redFlags: [
      { title: "Emergência imediata — interromper e acionar o SAMU (192) / pronto-socorro [P11] [consenso] (conduta)", tone: "emergency", items: [
        "**Falta de ar súbita ou dor no peito**, sobretudo com perna inchada ou após cirurgia/imobilização (sinais de embolia pulmonar descritos na diretriz [P11 — rec. 1.1.15]).",
      ] },
      { title: "Avaliação médica no mesmo dia [P11 — rec. 1.1.1 e 1.1.2] [consenso] (conduta)", tone: "sameDay", items: [
        "**Panturrilha ou perna inchada e dolorida**, principalmente após cirurgia, imobilização ou repouso prolongado (sinais de trombose venosa profunda).",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino", tone: "refer", items: [
        "**Trauma recente** com inchaço rápido, incapacidade de apoiar o peso ou dor forte (trauma recente é sinal atípico na diretriz NICE de artrose). **[consenso]**",
        "**Luxação** ou sensação de a patela \"sair do lugar\" [P1]. **[consenso]**",
        "**Joelho quente e inchado**, febre, travamento verdadeiro (o joelho \"trava\" e não estende) ou piora rápida — sinais atípicos que sugerem outro diagnóstico (descritos para artrose na diretriz NICE). **[consenso]**",
        "Sinais gerais (câncer, perda de peso sem explicação, dor noturna que impede dormir).",
      ] },
    ],
    avoidWords: ["cartilagem gasta", "joelho fraco", "patela fora do lugar", "nunca mais agache", "condromalácia"],
    phrases: [
      "\"Seu joelho aguenta carga; vamos aumentar aos poucos.\"",
      "\"Hoje o agachamento vai até a metade; ampliamos conforme melhorar.\"",
      "\"Fortalecer o quadril também ajuda o joelho.\"",
      "\"Um pouco de desconforto pode acontecer; se passar de 5/10 ou não voltar ao normal até amanhã, me avise.\"",
    ],
    references: [
      { id: "P1", text: "Crossley KM, Stefanik JJ, Selfe J, Collins NJ, Davis IS, Powers CM, et al. 2016 Patellofemoral pain consensus statement from the 4th International Patellofemoral Pain Research Retreat, Manchester. Part 1: Terminology, definitions, clinical examination, natural history, patellofemoral osteoarthritis and patient-reported outcome measures. Br J Sports Med. 2016;50(14):839-843.", url: "https://doi.org/10.1136/bjsports-2016-096384" },
      { id: "P2", text: "Crossley KM, van Middelkoop M, Callaghan MJ, Collins NJ, Rathleff MS, Barton CJ. 2016 Patellofemoral pain consensus statement from the 4th International Patellofemoral Pain Research Retreat, Manchester. Part 2: recommended physical interventions (exercise, taping, bracing, foot orthoses and combined interventions). Br J Sports Med. 2016;50(14):844-852.", url: "https://doi.org/10.1136/bjsports-2016-096268" },
      { id: "P3", text: "Collins NJ, Barton CJ, van Middelkoop M, Callaghan MJ, Rathleff MS, Vicenzino BT, et al. 2018 Consensus statement on exercise therapy and physical interventions (orthoses, taping and manual therapy) to treat patellofemoral pain: recommendations from the 5th International Patellofemoral Pain Research Retreat, Gold Coast, Australia, 2017. Br J Sports Med. 2018;52(18):1170-1178.", url: "https://doi.org/10.1136/bjsports-2018-099397" },
      { id: "P5", text: "Lack S, Barton C, Sohan O, Crossley K, Morrissey D. Proximal muscle rehabilitation is effective for patellofemoral pain: a systematic review with meta-analysis. Br J Sports Med. 2015;49(21):1365-1376.", url: "https://doi.org/10.1136/bjsports-2015-094723" },
      { id: "P8", text: "Powers CM, Ho KY, Chen YJ, Souza RB, Farrokhi S. Patellofemoral Joint Stress During Weight-Bearing and Non-Weight-Bearing Quadriceps Exercises. J Orthop Sports Phys Ther. 2014;44(5):320-327.", url: "https://doi.org/10.2519/jospt.2014.4936" },
      { id: "P11", text: "National Institute for Health and Care Excellence (NICE). Venous thromboembolic diseases: diagnosis, management and thrombophilia testing. NICE guideline NG158. Publicada em 26/03/2020, atualizada em 02/08/2023.", url: "https://www.nice.org.uk/guidance/ng158/chapter/Recommendations" },
    ],
  },
  joelho_artrose: {
    key: "joelho_artrose",
    title: "Artrose de joelho",
    source: "joelho-artrose.md",
    summary: [
      "**Exercício é tratamento central:** fortalecimento local + condicionamento aeróbico, com educação; perder peso ajuda quem tem sobrepeso (qualquer perda ajuda; 10% melhor que 5%).",
      "**Carga não \"gasta\" o joelho:** exercício com carga não mostrou dano à cartilagem; corrida recreativa não aumentou a artrose.",
      "**Avise que a dor pode aumentar no começo:** manter o exercício regular traz benefício a longo prazo.",
      "**Adapte se reproduzir sintomas:** amplitude, apoio, degrau mais baixo, sem salto — e progrida.",
      "**Monitore:** até 5/10 durante e de volta ao habitual até o dia seguinte → siga; mais dor ou inchaço → reduza.",
      "**Sinais de alerta:** joelho quente e inchado, febre, trauma recente, piora rápida ou deformidade, panturrilha inchada e dolorida → pare e encaminhe.",
      "**Fale de forma positiva:** \"articulação que se move e recebe carga fica mais forte\"; evite \"osso com osso\".",
    ],
    tables: [
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Agachamento livre com barra / Agachamento goblet", "Se doer no fundo", "Amplitude sem dor (ex.: sentar e levantar de um banco alto e ir baixando o banco); goblet em vez de barra", "consenso", "prática clínica"],
          ["Leg press 45°", "Se doer no fundo", "Amplitude menor; progredir a amplitude", "consenso", "prática clínica"],
          ["Afundo com halteres / Agachamento búlgaro", "Se doer ou faltar equilíbrio", "Passo mais curto, amplitude menor, apoio das mãos", "consenso", "prática clínica"],
          ["Step-up no banco", "Se doer ao subir ou descer", "Degrau mais baixo; descida controlada", "consenso", "prática clínica"],
          ["Burpee", "Se o impacto ou o agachamento fundo doerem", "Sem salto; descer até onde não doer; ou trocar por step-up", "consenso", "prática clínica"],
          ["Cadeira extensora", "Se doer em alguma parte do arco", "Amplitude sem dor; carga menor com mais repetições", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Costumam ajudar** (sem alerta): fortalecimento de quadríceps e quadril (cadeira extensora, leg press, cadeira abdutora, elevação pélvica), aeróbico de baixo impacto (caminhada, bicicleta) e exercícios de equilíbrio [A1, A3, A4]. **[forte]** para exercício em geral (as referências não definem exercícios específicos da biblioteca)",
    ],
    redFlags: [
      { title: "Emergência imediata — interromper e acionar o SAMU (192) / pronto-socorro [A11] [consenso] (conduta)", tone: "emergency", items: [
        "**Falta de ar súbita ou dor no peito**, sobretudo com perna inchada ou após cirurgia (ex.: prótese) ou imobilização (sinais de embolia pulmonar descritos na diretriz [A11 — rec. 1.1.15]).",
      ] },
      { title: "Avaliação médica no mesmo dia [A11 — rec. 1.1.1 e 1.1.2] [consenso] (conduta)", tone: "sameDay", items: [
        "**Panturrilha ou perna inchada e dolorida**, principalmente após cirurgia, imobilização ou repouso prolongado (sinais de trombose venosa profunda).",
        "**Joelho quente e inchado**, sobretudo com **febre** ou mal-estar (suspeita de infecção) [A1 — sinais atípicos].",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino — sinais atípicos que sugerem outro diagnóstico ou diagnóstico adicional [A1 — definição de sinais atípicos] [consenso] (diretriz)", tone: "refer", items: [
        "**Trauma recente.**",
        "**Rigidez matinal prolongada** (mais de 30 minutos; o critério clínico de artrose é até 30 minutos [A1 — rec. 1.1.1]).",
        "**Piora rápida** dos sintomas ou **deformidade** que aumenta rápido.",
        "Suspeita de **tumor** (ex.: história de câncer, perda de peso sem explicação, dor noturna que impede dormir).",
      ] },
    ],
    avoidWords: ["osso com osso", "joelho gasto/desgastado", "vai precisar de prótese", "não pode agachar", "exercício desgasta mais"],
    phrases: [
      "\"Articulação que se move e recebe carga fica mais forte; vamos aumentar aos poucos.\"",
      "\"No começo o joelho pode reclamar um pouco; com treino regular, isso costuma melhorar.\"",
      "\"Hoje o agachamento vai até onde estiver confortável; ampliamos depois.\"",
      "\"Se o joelho inchar ou a dor não voltar ao normal até amanhã, me avise para ajustarmos.\"",
      "\"Caminhar e pedalar também fazem bem para o seu joelho.\"",
    ],
    references: [
      { id: "A1", text: "National Institute for Health and Care Excellence (NICE). Osteoarthritis in over 16s: diagnosis and management. NICE guideline NG226. Publicada em 19/10/2022.", url: "https://www.nice.org.uk/guidance/ng226/chapter/Recommendations" },
      { id: "A3", text: "Kolasinski SL, Neogi T, Hochberg MC, Oatis C, Guyatt G, Block J, et al. 2019 American College of Rheumatology/Arthritis Foundation Guideline for the Management of Osteoarthritis of the Hand, Hip, and Knee. Arthritis Care Res. 2020;72(2):149-162.", url: "https://doi.org/10.1002/acr.24131" },
      { id: "A4", text: "Fransen M, McConnell S, Harmer AR, Van der Esch M, Simic M, Bennell KL. Exercise for osteoarthritis of the knee. Cochrane Database Syst Rev. 2015;CD004376.", url: "https://doi.org/10.1002/14651858.CD004376.pub3" },
      { id: "A11", text: "National Institute for Health and Care Excellence (NICE). Venous thromboembolic diseases: diagnosis, management and thrombophilia testing. NICE guideline NG158. Publicada em 26/03/2020, atualizada em 02/08/2023.", url: "https://www.nice.org.uk/guidance/ng158/chapter/Recommendations" },
    ],
  },
  dor_lombar_flexao: {
    key: "dor_lombar_flexao",
    title: "Dor lombar — intolerância à flexão",
    source: "lombalgia-inespecifica.md + hernia-discal-lombar-flexao.md",
    summary: [
      "**Padrão direcional:** os sintomas pioram ao flexionar a coluna ou ficar sentado — veja a tabela de cautela abaixo (mesma da hérnia discal lombar).",
      "**Mantenha o aluno ativo:** exercício é tratamento de primeira linha na dor crônica; nenhum tipo é claramente superior — escolha o que ele gosta e consegue manter.",
      "**Adapte, não proíba:** sem alerta automático; se um exercício reproduzir sintomas, ajuste amplitude, carga, apoio, cadência, posição e volume. Nenhum exercício a evitar por padrão.",
      "**Guie-se pelos sintomas, não pelo laudo:** achados de imagem são comuns em pessoas sem dor.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual no dia seguinte → siga/progrida; acima disso → reduza.",
      "**Progrida aos poucos:** 2–10% de carga quando sobrarem 1–2 repetições além do alvo.",
      "**Sinais de alerta** (bexiga/intestino, dormência na \"sela\", fraqueza que piora, câncer, febre, perda de peso, trauma) → pare e encaminhe.",
      "**Fale de forma positiva:** \"sua coluna é forte e se adapta\"; evite \"desgaste\", \"coluna frágil\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Abdominal supra", "Flexão lombar repetida", "Isometrias: dead bug, prancha, Pallof press", "consenso", "prática clínica"],
          ["Elevação de pernas deitado", "Tende a levar a lombar à flexão no fim da amplitude", "Joelhos flexionados, amplitude menor sem tirar a lombar do apoio, ou dead bug", "consenso", "prática clínica"],
          ["Levantamento terra / Levantamento terra romeno", "Flexão sob carga; pressão no disco maior com costas curvadas e carga longe do corpo", "Barra elevada (blocos/rack), carga junto ao corpo, amplitude até onde não há sintomas; progredir conforme tolerância", "fraca (mecanismo)", "[H14] + prática clínica"],
          ["Remada curvada com barra", "Tronco inclinado sustentado sob carga", "Remada unilateral apoiada no banco ou remada baixa na polia com tronco ereto", "fraca (mecanismo)", "[H14] + prática clínica"],
          ["Leg press 45°", "No fundo do movimento a pelve pode \"enrolar\" (flexão lombar sob carga)", "Limitar a amplitude antes da retroversão da pelve", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Agachamento livre com barra", "Se reproduzir sintomas (flexão lombar no fundo)", "Agachar até uma caixa na altura sem sintomas; agachamento goblet", "consenso", "prática clínica"],
          ["Kettlebell swing", "Fase de crise", "Reduzir carga e ritmo; trocar temporariamente por elevação pélvica", "consenso", "prática clínica"],
          ["Burpee", "Fase de crise", "Versão sem salto e mais lenta, ou retirar temporariamente", "consenso", "prática clínica"],
          ["Elevação pélvica", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Ponte de glúteos", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Alavancas de adaptação",
        kind: "guide",
        columns: ["Alavanca", "Como aplicar", "Nível", "Referência"],
        rows: [
          ["Amplitude", "Reduzir a amplitude à faixa sem piora e ampliar aos poucos (ex.: agachar até uma caixa).", "consenso", "prática clínica"],
          ["Carga", "Reduzir a carga e progredir 2–10% conforme tolerância.", "consenso", "[R17] (extrapolado)"],
          ["Apoio", "Acrescentar apoio (banco, parede, máquina) para diminuir a exigência de estabilização.", "consenso", "prática clínica"],
          ["Cadência", "Execução controlada; evitar rebotes e movimentos balísticos enquanto houver piora.", "consenso", "prática clínica"],
          ["Posição", "Trocar a variação (ex.: em pé → apoiado; carga axial → carga à frente).", "consenso", "prática clínica"],
          ["Volume", "Menos séries/repetições na crise; retomar gradualmente.", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir. Nesta condição a cautela é **direcional**: exercícios com flexão lombar sob carga, repetida ou sustentada. O alerta não bloqueia o treino; lembra o professor de ajustar. A mesma tabela vale para **\"Dor lombar — intolerância à flexão\"** (sem laudo).",
      "**Costumam ser bem tolerados** (sem alerta; confirmar pelos sintomas): ponte de glúteos e elevação pélvica (com a técnica acima), bird dog, prancha frontal e lateral, Pallof press, caminhada. **[consenso]** — prática clínica.",
      "**Horário:** evitar concentrar exercícios de flexão lombar logo após acordar [H15]. **[fraca]** (extrapolado)",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia (suspeita de síndrome da cauda equina) [R19]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino** (ex.: dificuldade para urinar, perda de controle).",
        "**Dormência ou formigamento na região da \"sela\"** (nádegas, parte interna das coxas, região genital) (baixo).",
        "Dor irradiada para **uma ou as duas pernas** com perda de sensibilidade ou **fraqueza** que está **piorando**.",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino [R19; R1 — 1.1.1] (o modelo usa \"referenciação urgente\", em até 5 dias, conforme o grau de suspeita)", tone: "refer", items: [
        "**História de câncer** (ex.: mama, próstata, pulmão, rim, tireoide) (baixo).",
        "**Perda de peso sem explicação** (mais de 5% em 6 meses) (alta).",
        "**Febre** junto da dor (baixo); **imunossupressão** (ex.: diabetes, HIV, artrite reumatoide, infecção prévia, consumo excessivo de álcool, uso prolongado de corticoide) — suspeita de infecção (baixo).",
        "Suspeita de **fratura**: trauma importante (ex.: queda de 5 degraus ou de 90 cm) (elevado); mudança súbita de postura com aumento da dor em quem tem osteoporose conhecida (baixo); uso prévio de corticoide (> 5 mg por 3 meses).",
        "**Dor noturna** que impede voltar a dormir e obriga a levantar; piora progressiva, dor em faixa, incapacidade de ficar deitado (baixo).",
        "Suspeita de doença inflamatória (ex.: espondiloartrite) [R1 — 1.1.1].",
      ] },
    ],
    avoidWords: ["desgaste", "coluna degenerada", "disco saiu do lugar", "coluna frágil/instável", "nunca dobre as costas", "isso vai piorar sua hérnia"],
    phrases: [
      "\"Sua coluna é forte e se adapta ao treino. Vamos aumentar aos poucos.\"",
      "\"Movimento ajuda na recuperação. Mantenha suas atividades do dia a dia.\"",
      "\"Um pouco de desconforto durante o exercício pode acontecer. Se passar de 5/10 ou não voltar ao normal até amanhã, me avise para ajustarmos.\"",
      "\"Hoje faremos este exercício com menos amplitude; vamos ampliar conforme você se sentir bem.\"",
      "\"Achados em exames são comuns em pessoas sem dor. O que guia o treino é como você se sente.\"",
      "\"Na crise, prefira se movimentar dentro do confortável em vez de ficar parado.\"",
    ],
    references: [
      { id: "H14", text: "Wilke H, Neef P, Caimi M, Hoogland T, Claes LE. New In Vivo Measurements of Pressures in the Intervertebral Disc in Daily Life. Spine. 1999;24(8):755-762.", url: "https://doi.org/10.1097/00007632-199904150-00005" },
      { id: "H15", text: "Snook SH, Webster BS, McGorry RW, Fogleman MT, McCann KB. The Reduction of Chronic Nonspecific Low Back Pain Through the Control of Early Morning Lumbar Flexion. Spine. 1998;23(23):2601-2607.", url: "https://doi.org/10.1097/00007632-199812010-00015" },
      { id: "R1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "R17", text: "American College of Sports Medicine. Progression Models in Resistance Training for Healthy Adults (position stand). Med Sci Sports Exerc. 2009;41(3):687-708.", url: "https://doi.org/10.1249/MSS.0b013e3181915670" },
      { id: "R19", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
  dor_lombar_extensao: {
    key: "dor_lombar_extensao",
    title: "Dor lombar — intolerância à extensão",
    source: "lombalgia-inespecifica.md + estenose-lombar-extensao.md",
    summary: [
      "**Padrão direcional:** os sintomas pioram ao arquear a coluna ou ficar muito tempo em pé — veja a tabela de cautela abaixo (mesma da estenose e da espondilolistese).",
      "**Mantenha o aluno ativo:** exercício é tratamento de primeira linha na dor crônica; nenhum tipo é claramente superior — escolha o que ele gosta e consegue manter.",
      "**Adapte, não proíba:** sem alerta automático; se um exercício reproduzir sintomas, ajuste amplitude, carga, apoio, cadência, posição e volume. Nenhum exercício a evitar por padrão.",
      "**Guie-se pelos sintomas, não pelo laudo:** achados de imagem são comuns em pessoas sem dor.",
      "**Monitore a dor:** até 5/10 durante e de volta ao habitual no dia seguinte → siga/progrida; acima disso → reduza.",
      "**Progrida aos poucos:** 2–10% de carga quando sobrarem 1–2 repetições além do alvo.",
      "**Sinais de alerta** (bexiga/intestino, dormência na \"sela\", fraqueza que piora, câncer, febre, perda de peso, trauma) → pare e encaminhe.",
      "**Fale de forma positiva:** \"sua coluna é forte e se adapta\"; evite \"desgaste\", \"coluna frágil\".",
    ],
    tables: [
      {
        title: "Gera alerta de cautela no montador",
        kind: "alert",
        columns: ["Exercício", "Por que cautela", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Extensão lombar no banco romano", "Extensão lombar repetida", "Amplitude só até o neutro, sem hiperextensão; ou bird dog", "fraca (mecanismo)", "[E5] + prática clínica"],
          ["Desenvolvimento militar com barra", "Em pé com carga acima da cabeça, tendência a arquear a lombar", "Sentado com apoio nas costas, ou halteres/landmine, sem arquear a lombar", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Adaptar se reproduzir sintomas (sem alerta)",
        kind: "guide",
        columns: ["Exercício", "Quando adaptar", "Como adaptar", "Nível", "Referência"],
        rows: [
          ["Elevação pélvica", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Ponte de glúteos", "Sempre (técnica)", "No topo, terminar com retroversão da pelve, sem hiperestender", "consenso", "prática clínica"],
          ["Pullover com halter", "Se arquear a lombar no alongamento", "Amplitude menor; lombar apoiada no banco", "consenso", "prática clínica"],
          ["Prancha frontal", "Se o quadril \"cair\" (lombar em extensão)", "Apoio nos joelhos; tempo menor", "consenso", "prática clínica"],
          ["Agachamento búlgaro / Afundo com halteres", "Se a perna de trás levar a lombar à extensão", "Passada menor; tronco levemente inclinado à frente", "consenso", "prática clínica"],
          ["Levantamento terra", "Se \"passar do ponto\" no fim (hiperextensão)", "Terminar com quadril e tronco alinhados", "consenso", "prática clínica"],
          ["Exercícios longos em pé", "Sintomas ao ficar em pé", "Intercalar com pausas sentado; versões sentadas", "consenso", "prática clínica"],
        ],
      },
      {
        title: "Alavancas de adaptação",
        kind: "guide",
        columns: ["Alavanca", "Como aplicar", "Nível", "Referência"],
        rows: [
          ["Amplitude", "Reduzir a amplitude à faixa sem piora e ampliar aos poucos (ex.: agachar até uma caixa).", "consenso", "prática clínica"],
          ["Carga", "Reduzir a carga e progredir 2–10% conforme tolerância.", "consenso", "[R17] (extrapolado)"],
          ["Apoio", "Acrescentar apoio (banco, parede, máquina) para diminuir a exigência de estabilização.", "consenso", "prática clínica"],
          ["Cadência", "Execução controlada; evitar rebotes e movimentos balísticos enquanto houver piora.", "consenso", "prática clínica"],
          ["Posição", "Trocar a variação (ex.: em pé → apoiado; carga axial → carga à frente).", "consenso", "prática clínica"],
          ["Volume", "Menos séries/repetições na crise; retomar gradualmente.", "consenso", "prática clínica"],
        ],
      },
    ],
    notes: [
      "**Princípio:** adaptar em vez de proibir. Nesta condição a cautela é **direcional**: exercícios que levam a lombar à **extensão** (arquear), sob carga ou sustentada, e ficar muito tempo em pé. O alerta não bloqueia o treino.",
      "**Costumam ser bem tolerados** (sem alerta; confirmar pelos sintomas): bicicleta ergométrica [E9, E10], exercícios em flexão [E10], leg press 45°, exercícios sentados ou apoiados, remadas sentadas, caminhada em intervalos. **[consenso]** (as referências indicam uso nos programas testados, não superioridade).",
    ],
    redFlags: [
      { title: "Emergência — encaminhar a serviço de urgência no mesmo dia (suspeita de síndrome da cauda equina) [R19]", tone: "sameDay", items: [
        "Alteração na função da **bexiga ou do intestino** (ex.: dificuldade para urinar, perda de controle).",
        "**Dormência ou formigamento na região da \"sela\"** (nádegas, parte interna das coxas, região genital) (baixo).",
        "Dor irradiada para **uma ou as duas pernas** com perda de sensibilidade ou **fraqueza** que está **piorando**.",
      ] },
      { title: "Encaminhar para avaliação antes de seguir com o treino [R19; R1 — 1.1.1] (o modelo usa \"referenciação urgente\", em até 5 dias, conforme o grau de suspeita)", tone: "refer", items: [
        "**História de câncer** (ex.: mama, próstata, pulmão, rim, tireoide) (baixo).",
        "**Perda de peso sem explicação** (mais de 5% em 6 meses) (alta).",
        "**Febre** junto da dor (baixo); **imunossupressão** (ex.: diabetes, HIV, artrite reumatoide, infecção prévia, consumo excessivo de álcool, uso prolongado de corticoide) — suspeita de infecção (baixo).",
        "Suspeita de **fratura**: trauma importante (ex.: queda de 5 degraus ou de 90 cm) (elevado); mudança súbita de postura com aumento da dor em quem tem osteoporose conhecida (baixo); uso prévio de corticoide (> 5 mg por 3 meses).",
        "**Dor noturna** que impede voltar a dormir e obriga a levantar; piora progressiva, dor em faixa, incapacidade de ficar deitado (baixo).",
        "Suspeita de doença inflamatória (ex.: espondiloartrite) [R1 — 1.1.1].",
      ] },
    ],
    avoidWords: ["desgaste", "coluna degenerada", "disco saiu do lugar", "coluna frágil/instável", "nunca dobre as costas", "isso vai piorar sua hérnia"],
    phrases: [
      "\"Sua coluna é forte e se adapta ao treino. Vamos aumentar aos poucos.\"",
      "\"Movimento ajuda na recuperação. Mantenha suas atividades do dia a dia.\"",
      "\"Um pouco de desconforto durante o exercício pode acontecer. Se passar de 5/10 ou não voltar ao normal até amanhã, me avise para ajustarmos.\"",
      "\"Hoje faremos este exercício com menos amplitude; vamos ampliar conforme você se sentir bem.\"",
      "\"Achados em exames são comuns em pessoas sem dor. O que guia o treino é como você se sente.\"",
      "\"Na crise, prefira se movimentar dentro do confortável em vez de ficar parado.\"",
    ],
    references: [
      { id: "E5", text: "Schmid MR, Stucki G, Duewell S, Wildermuth S, Romanowski B, Hodler J. Changes in cross-sectional measurements of the spinal canal and intervertebral foramina as a function of body position: in vivo studies on an open-configuration MR system. AJR Am J Roentgenol. 1999;172(4):1095-1102.", url: "https://doi.org/10.2214/ajr.172.4.10587155" },
      { id: "E9", text: "Minetama M, Kawakami M, Teraguchi M, Kagotani R, Mera Y, Sumiya T, et al. Supervised physical therapy vs. home exercise for patients with lumbar spinal stenosis: a randomized controlled trial. Spine J. 2019;19(8):1310-1318.", url: "https://doi.org/10.1016/j.spinee.2019.04.009" },
      { id: "E10", text: "Pua YH, Cai CC, Lim KC. Treadmill walking with body weight support is no more effective than cycling when added to an exercise program for lumbar spinal stenosis: a randomised controlled trial. Aust J Physiother. 2007;53(2):83-89.", url: "https://doi.org/10.1016/S0004-9514(07)70040-5" },
      { id: "R1", text: "National Institute for Health and Care Excellence (NICE). Low back pain and sciatica in over 16s: assessment and management (NG59). Publicado em 30/11/2016; última atualização em 29/07/2026.", url: "https://www.nice.org.uk/guidance/ng59" },
      { id: "R17", text: "American College of Sports Medicine. Progression Models in Resistance Training for Healthy Adults (position stand). Med Sci Sports Exerc. 2009;41(3):687-708.", url: "https://doi.org/10.1249/MSS.0b013e3181915670" },
      { id: "R19", text: "Finucane LM, Downie A, Mercer C, Greenhalgh SM, Boissonnault WG, Pool-Goudzwaard AL, et al. International Framework for Red Flags for Potential Serious Spinal Pathologies. J Orthop Sports Phys Ther. 2020;50(7):350-372.", url: "https://doi.org/10.2519/jospt.2020.9971" },
    ],
  },
};
